### ISSUE TITLE
Security: Multiple CVEs

### ISSUE THREAD

**Issue by binarious** [agnitas-org/openemm#8]
I ran a [dependency check](https://www.owasp.org/index.php/OWASP_Dependency_Check) on https://github.com/agnitas-org/openemm/tree/master/frontend/lib, because I found some old versions there. These are the results:
Dependencies Scanned: 137 (110 unique)
Vulnerable Dependencies: 16
Vulnerabilities Found: 83

Small excerpt:
<img width="1147" alt="grafik" src="https://user-images.githubusercontent.com/200375/68935980-ced9ea80-0799-11ea-9add-3208b7b0f3f4.png">

There are a lot of critical ones including authentication bypasses. Are these all false-positives?

**Comment by agnitas-org** [comment]
Not all of these are false positives. But, for example, we fixed the known Struts 1 vulnerabilities ourselves in the code because of its EOL. Some of the exploits do not work in the OpenEMM environment. Other issues will be addressed since we plan to replace libraries with our switch to Java 11, anyway.
Right now we are in the process of discussion how to communicate these issues in a timely and transparent way.
BTW, we do penetration tests on the deployed software about once a year by professional pen testers.

**Comment by agnitas-org** [comment]
We have updated some 3rd party components in OpenEMM 20.04 and will continue to do so. We implemented an internal process to analyze and to evaluate the results of the OWASP dependency check for Java and Javascript.
